name: Run Python Game

on:
  push:
    branches: 
      - master
      - main
  pull_request:
    branches: 
      - master
      - main

  workflow_dispatch:

jobs:
  run-game:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Pygame
      run: |
        python -m pip install --upgrade pip
        pip install pygame

    - name: Run Alien Invasion Game
      run: |
        python alien_invasion.py

